apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  ports:
  - port: {{ .Values.ingress.port }}
    targetPort: {{ .Values.app.port }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.app.name }}